AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-step-functions

  Sample SAM Template for sam-step-functions
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60

Resources:
  ## Define a API /credenciadora/conjuntos-unidades-recebiveis
  ## Essa API irá chamar a "aplicação" - uma lambda que irá iniciar a StepFunctionsStateMachine
  ConjuntoRecebiveisFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        RegistraContrato:
          Type: Api 
          Properties:
            Path: /credenciadora/conjuntos-unidades-recebiveis
            Method: post
    Metadata:
      DockerTag: nodejs10.x-v1
      DockerContext: ./conjuntos-unidades-recebiveis
      Dockerfile: Dockerfile

  LotesRecebiveisFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        EnviaLotes:
          Type: Api 
          Properties:
            Path: /credenciadora/conjuntos-unidades-recebiveis/{id_conjunto}/lotes-unidades-recebiveis
            Method: post
    Metadata:
      DockerTag: nodejs10.x-v1
      DockerContext: ./lotes-unidades-recebiveis
      Dockerfile: Dockerfile

  OperacoesFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        Operacoes:
          Type: Api 
          Properties:
            Path: /credenciadora/operacoes
            Method: post
    Metadata:
      DockerTag: nodejs10.x-v1
      DockerContext: ./operacoes
      Dockerfile: Dockerfile

  RetornosRegistroOperacaoFunction:
    Type: AWS::Serverless::Function 
    Properties:
      PackageType: Image
      Events:
        RetornoRegistroOperacao:
          Type: Api 
          Properties:
            Path: /credenciadora/retornos-registro-operacao
            Method: post
    Metadata:
      DockerTag: nodejs10.x-v1
      DockerContext: ./retornos-registro-operacao
      Dockerfile: Dockerfile

## Definição da máquina de estado que fará a implementação do padrão SAGA
## o descritor da máquina está no arquivo ASL.JSON
## ajustar políticas para um ambiente de produção - SOMENTE USAR EM TESTES / EXEMPLO
  R2C3SAGAStateMachine: 
    Type: AWS::Serverless::StateMachine
    Properties: 
      Name: R2C3-SAGA
      Type: STANDARD
      DefinitionUri: statemachine/r2c3.asl.json
      Logging: 
        LoggingConfiguration:
          Destinations: 
            - CloudWatchLogsLogGroup: 
          IncludeExecutionData: true
          Level: ALL
      Tracing: 
        Enabled: true 
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonECSFullAccess

  # Tabela usada pela máquina de estado do R2C3
  R2C3DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: R2C3-SAGA
      BillingMode: PAY_PER_REQUEST
      KeySchema: 
        - AttributeName: ISPB
          KeyType: HASH
        - AttributeName: OPERACAO
          KeyType: RANGE 
      SSESpecification:
        SSEEnabled: true
      
  AtlanteSAGAStateMachine: 
    Type: AWS::Serverless::StateMachine
    Properties: 
      Name: Atlante-R2C3-SAGA
      Type: STANDARD
      DefinitionUri: statemachine/atlante.asl.json
      Logging: 
        LoggingConfiguration:
          Destinations: 
            - CloudWatchLogsLogGroup: 
          IncludeExecutionData: true
          Level: ALL
      Tracing: 
        Enabled: true 
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaBasicExecutionRole
        - AmazonS3FullAccess
        - AmazonECSFullAccess

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  URLdaApi:
    Description: "API Gateway endpoint URL for Prod stage f"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  ConjuntoRecebiveisFunction:
    Description: "ConjuntoRecebiveis Lambda Function ARN"
    Value: !GetAtt ConjuntoRecebiveisFunction.Arn
  LotesRecebiveisFunction:
    Description: "LotesRecebiveis Lambda Function ARN"
    Value: !GetAtt LotesRecebiveisFunction.Arn
  OperacoesFunction:
    Description: "Operacoes Lambda Function ARN"
    Value: !GetAtt OperacoesFunction.Arn
  RetornosRegistroOperacaoFunction:
    Description: "RetornosRegistroOperacao Lambda Function ARN"
    Value: !GetAtt OperacoesFunction.Arn